version: "3"
services:
    php:
        container_name: lilliputs_php
        build: ./code
        restart: always
        command: >
            php-fpm
        working_dir: /code
        ports: 
            - 8000:8000
        expose:
            - "8000"
        volumes:
            - ./code:/code
            - ./code/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - ./code/php.ini:/usr/local/etc/php/php.ini
    nginx:
        container_name: lilliputs_nginx
        image: nginx:1.19
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./code/public:/public
            - ./code/storage/app/public:/public/uploads
        depends_on:
            - php
    db:
        container_name: lilliputs_db
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE: $DB_DATABASE_LIL
            MYSQL_USER: $DB_USERNAME_LIL
            MYSQL_PASSWORD: $DB_PASSWORD_LIL
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD_LIL
            MYSQL_TCP_PORT: 3306
            TZ: 'Asia/Tokyo'
        volumes: 
            - ./mysql/data:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports: 
            - 3306:3306
