version: "3"
services:
    php:
        container_name: lilliputs_php
        build: ./code
        restart: always
        command: >
            php-fpm
        working_dir: /code
        ports: 
            - 8000:8000
        expose:
            - "8000"
        volumes:
            - ./code:/code
            - ./code/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - ./code/php.ini:/usr/local/etc/php/php.ini
    nginx:
        container_name: larast_nginx
        image: nginx:1.19
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./code/public:/public
        depends_on:
            - php
